# SwiftLint Configuration
# https://realm.github.io/SwiftLint/

# Paths to exclude from linting
excluded:
  - Pods
  - .build
  - AnonymousWallIos.xcodeproj
  - AnonymousWallIos/Preview Content
  - build
  - DerivedData

# Enabled rules
opt_in_rules:
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - empty_count
  - empty_string
  - explicit_init
  - first_where
  - force_unwrapping
  - implicitly_unwrapped_optional
  - literal_expression_end_indentation
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - redundant_nil_coalescing
  - redundant_type_annotation
  - sorted_first_last
  - trailing_closure
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces

# Disabled rules
disabled_rules:
  - todo
  - trailing_comma

# Rule configurations
line_length:
  warning: 120
  error: 150
  ignores_comments: true
  ignores_urls: true
  ignores_function_declarations: true

type_body_length:
  warning: 300
  error: 400

file_length:
  warning: 500
  error: 1000
  ignore_comment_only_lines: true

function_body_length:
  warning: 50
  error: 100

cyclomatic_complexity:
  warning: 10
  error: 20

type_name:
  min_length: 3
  max_length: 40

identifier_name:
  min_length: 2
  max_length: 60
  excluded:
    - id
    - url
    - URL
    - ok

large_tuple:
  warning: 3
  error: 4

nesting:
  type_level: 2
  statement_level: 5

# Custom rules can be added here
# custom_rules:
