//
//  Color+Theme.swift
//  AnonymousWallIos
//
//  Theme colors extension for college-friendly UI
//
//  Note: Color assets (primaryPurple, primaryPink, vibrantOrange, vibrantTeal, softPurple)
//  are auto-generated by Xcode from the asset catalog and available as Color.primaryPurple, etc.

import SwiftUI

extension Color {
    // Gradient combinations for modern look
    // Uses auto-generated color symbols from asset catalog
    static var purplePinkGradient: LinearGradient {
        LinearGradient(
            colors: [.primaryPurple, .primaryPink],
            startPoint: .topLeading,
            endPoint: .bottomTrailing
        )
    }
    
    static var tealPurpleGradient: LinearGradient {
        LinearGradient(
            colors: [.vibrantTeal, .softPurple],
            startPoint: .leading,
            endPoint: .trailing
        )
    }
    
    static var orangePinkGradient: LinearGradient {
        LinearGradient(
            colors: [.vibrantOrange, .primaryPink],
            startPoint: .topLeading,
            endPoint: .bottomTrailing
        )
    }
}
